### ISSUE TITLE
Long date in the name of the asset

### ISSUE THREAD

**Issue by coliss86** [WebFreak001/deploy-nightly#11]
Hi, 

Thanks for your work 💪 

I would like to have a longer date in the name of the asset, like `YYYYMMDD-HHMM`.

Is there a way to configure this please ?

Thanks !

**Comment by WebFreak001** [comment]
I think given the simplicity of the action it'd be best if you fork the action and change it in your branch, avoids potential issues with config parsing and needing to interpret it as well.

For your suggestion you need to change

https://github.com/WebFreak001/deploy-nightly/blob/c66feb4ee96031f4ad91b92e44617ead2d473f1b/index.js#L85

to

```js
let date = now.getUTCFullYear().toString() + pad2((now.getUTCMonth() + 1).toString()) + pad2(now.getUTCDate().toString())
    + "-" + pad2(now.getUTCHours().toString()) + pad2(now.getUTCMinutes().toString());
```

and you can also change the layout entirely how you want to.

As this extension uses JS directly and has the node_modules also checked into master, you can just edit directly online on GitHub with the edit button at the top right and the action should just work in GH actions.

Where you want to use it you would then just use `coliss86/deploy-nightly@master` or `coliss86/deploy-nightly@commithash` instead of `WebFreak001/deploy-nightly@v1.1.0`

**Comment by coliss86** [comment]
Very nice answer !
Thanks
