### ISSUE TITLE
 Upload multiple files (xgo)

### ISSUE THREAD

**Issue by slashtechno** [WebFreak001/deploy-nightly#15]
I want to publish nightly build of my Go projects.
How can I publish the multiple files that [xgo](https://github.com/marketplace/actions/golang-cgo-cross-compiler) creates? When I was reading the example workflow configuration for `deploy-nightly`, it seems that only one file can be uploaded. Is it possible to upload an entire folder instead?

**Comment by WebFreak001** [comment]
if you want to distribute multiple files for one target platform you should create an archive using the built-in archiving tools, e.g. 7z is preinstalled on github actions machines.

Otherwise GitHub doesn't support uploading folders, only individual files. But we could integrate folder zipping into this action (although typical archive formats depend on the target platform)

**Comment by slashtechno** [comment]
> if you want to distribute multiple files for one target platform you should create an archive using the built-in archiving tools, e.g. 7z is preinstalled on github actions machines.
> 
> Otherwise GitHub doesn't support uploading folders, only individual files. But we could integrate folder zipping into this action (although typical archive formats depend on the target platform)

Oh, okay. Initially, I misunderstood what this action was meant for.
